#!/usr/bin/env bash
# Compile the M3 triangle shaders to SPIR-V and emit them as C uint32_t arrays
# in tri_shaders.h (embedded into nvk_tri.c — no on-device shader compiler).
#   docker run --rm -v "D:\switch-nvk:/work" -w /work switch-nvk-build bash winsys/smoke/shaders/gen-shaders.sh
set -e
cd "$(dirname "$0")"
glslangValidator -V triangle.vert -o triangle.vert.spv
glslangValidator -V triangle.frag -o triangle.frag.spv
python3 - <<'PY'
import struct
def emit(name, path, out):
    data = open(path,'rb').read()
    assert len(data) % 4 == 0, "SPIR-V not word-aligned"
    words = struct.unpack('<%dI' % (len(data)//4), data)
    out.write('static const uint32_t %s[] = {\n' % name)
    for i in range(0, len(words), 8):
        out.write('  ' + ', '.join('0x%08x' % w for w in words[i:i+8]) + ',\n')
    out.write('};\n')
    out.write('static const unsigned %s_sz = %d; /* bytes */\n\n' % (name, len(data)))
with open('tri_shaders.h','w') as o:
    o.write('/* generated by gen-shaders.sh from triangle.{vert,frag} — do not edit */\n')
    o.write('#pragma once\n#include <stdint.h>\n\n')
    emit('tri_vert_spv','triangle.vert.spv',o)
    emit('tri_frag_spv','triangle.frag.spv',o)
print('wrote tri_shaders.h (vert + frag SPIR-V)')
PY
ls -la tri_shaders.h triangle.vert.spv triangle.frag.spv
